#!/bin/sh
# This script is called by sinit on boot.

PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo "System is starting up."
echo
echo "suzaku: stage 1"
echo

echo "Mounting API filesystem."
	mkdir -p /dev/pts
	mkdir /dev/shm
	mountpoint -q /proc    || mount -t proc proc /proc -o nosuid,noexec,nodev
	mountpoint -q /sys     || mount -t sysfs sys /sys -o nosuid,noexec,nodev
	mountpoint -q /var/run || mount -t tmpfs run /run -o mode=0775,nosuid,nodev
	mountpoint -q /dev     || mount -t devtmpfs dev /dev -o mode=0755,nosuid
	mountpoint -q /dev/pts || mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
	mountpoint -q /dev/shm || mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev

echo "Checking filesystems."
	fsck -A -T -C -a || echo "Filesystem check failed. Panic."

echo "Mounting tmpfs."
	mount -t tmpfs tmpfs /tmp -o mode=1777,nosuid,nodev

echo "Mounting partitions."
	mount -a
	mount -o remount,rw /

echo "Initializing eudev."
	/sbin/udevd --daemon
	/sbin/udevadm trigger --action=add --type=subsystems
	/sbin/udevadm trigger --action=add --type=devices

echo "Mounting swap."
	swapon -a

/sbin/agetty -J -8 -s 38400 tty1 linux &
