#!/bin/sh
# This script is called by sinit on boot.
# It performs one time tasks that don't require configuration
# and are the bare minimum to get the system up and running.
# This should never fail.

PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo
echo "suzaku: Taking flight..."
echo

echo "Mounting pseudo-filesystems."
	mountpoint -q /proc    || mount -t proc proc /proc -o nosuid,noexec,nodev
	mountpoint -q /sys     || mount -t sysfs sys /sys -o nosuid,noexec,nodev
	mountpoint -q /var/run || mount -t tmpfs run /run -o mode=0775,nosuid,nodev
	mountpoint -q /dev     || mount -t devtmpfs dev /dev -o mode=0755,nosuid

	mkdir /dev/pts /dev/shm
	mountpoint -q /dev/pts || mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
	mountpoint -q /dev/shm || mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev

echo "Checking filesystems."
	fsck -A -T -C -a || echo "Filesystem check failed. Panic."

echo "Mounting tmpfs."
	mount -t tmpfs tmpfs /tmp -o mode=1777,nosuid,nodev

echo "Mounting partitions."
	mount -a
	mount -o remount,rw /

echo "Initializing eudev."
	udevd --daemon
	udevadm trigger --action=add --type=subsystems
	udevadm trigger --action=add --type=devices

echo "Setting system clock."
	hwclock --systz

# Enter flight stage.
exec /etc/suzaku/flight
