#!/bin/sh
# This script is called when a shutdown is requested.
# It kills the process supervisor and does all the tasks 
# necessary for a clean shutdown.

PATH=/bin:/sbin:/usr/bin:/usr/sbin
. /etc/suzaku.conf

echo
echo "suzaku: Landing..."
echo

echo "Unmounting swap."
	swapoff -a

echo "Shutting down eudev."
	killall udevd

echo "Stopping services."
	s6-svscanctl -an /run/suzaku

echo "Sending all processes the TERM signal."
	/sbin/toybox killall5 -TERM
	sleep 3

echo "Sending all processes the KILL signal."
	/sbin/toybox killall5 -KILL

echo "Unmounting partitions."
	umount /tmp
	umount -a -r -t nosysfs,noproc,nodevtmpfs,notmpfs

echo "Remounting root read-only."
	mount -o remount,ro /
